name: lint and test
on: [push]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest] #, macOS-latest, windows-latest]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pdm test and checks
        run: |
          pdm sync -d -G lint,check,test
          pdm run lint
          pdm run check
          pdm run test
